Repository U-Mate/front, pull requests merged in 2025-06, with the labels that each got.

#40 Feat/대표 페이지-로그인전-모바일 구현&푸터 위치 뷰포트 바깥으로만 보이게 수정&헤더에 hasShadow 속성 추가
  src/components/Button.tsx
  src/components/ChatbotButton.tsx
  src/components/EventBanner/EventBannerCard.tsx
  src/components/Header.tsx
  src/components/LoginBanner.tsx
  src/components/PlanCardSmall.tsx
  src/default.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/router/index.tsx
Labels: refactoring, style

#41 Feat/바로가기페이지
  public/images/shortcut/shortcut-main-big.png
  public/images/shortcut/shortcut-phone.png
  public/images/shortcut/shortcut-webchatbot.png
  src/components/Header.tsx
  src/components/shortcut/ShortcutCard.tsx
  src/components/shortcut/ShortcutCarousel.tsx
  src/components/shortcut/ShortcutWeb.tsx
  src/pages/ShortcutPage.tsx
  src/router/index.tsx
Labels: feat

#42 Feat/모달 접근성 고려 및 리뷰 모달 컴포넌트 분리
  package-lock.json
  package.json
  src/components/Modal/BaseModal.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/Review/ReviewListContent.tsx
  src/components/Modal/Review/ReviewModal.tsx
  src/components/Modal/Review/ReviewWriteContent.tsx
  src/components/Modal/ReviewModal.tsx
  src/index.css
  src/router/index.tsx
Labels: refactoring

#44 feat : 더보기 메뉴 UI 구성
  src/components/BottomSheet/BottomSheet.tsx
  src/components/BottomSheet/SolutionList.tsx
  src/router/index.tsx
Labels: feat

#45 Feat/요금제 페이지 구현
  src/apis/PlansApi.ts
  src/apis/axiosInstance.ts
  src/components/BenefitCard.tsx
  src/components/Button.tsx
  src/components/Header.tsx
  src/components/Modal/BaseModal.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/FilterModal.tsx
  src/components/PlanCard.tsx
  src/components/PlanCardLarge.tsx
  src/components/PlanCardSmall.tsx
  src/data/benefitsCard.ts
  src/default.tsx
  src/hooks/useDebounce.ts
  src/pages/PricingPage.tsx
  src/utils/getDiscountFee.ts
Labels: feat, fix, style

#46 Feat/회원가입페이지 구현
  src/apis/auth.ts
  src/apis/axios.ts
  src/components/InputField.tsx
  src/components/suffixButtons.tsx
  src/pages/RegisterPage.tsx
  src/router/index.tsx
  src/types/member.ts
  src/utils/formatBirth.ts
  src/utils/formatTimer.ts
Labels: feat

#52 Feat/로그인페이지
  .gitignore
  src/apis/auth.ts
  src/apis/axiosInst.ts
  src/components/Header.tsx
  src/components/InputField.tsx
  src/components/Modal/AccountStepRenderer.tsx
  src/components/Modal/FindAccountModal.tsx
  src/components/Modal/ResetPasswordModal.tsx
  src/components/suffixButtons.tsx
  src/default.tsx
  src/main.tsx
  src/pages/LoginPage.tsx
  src/router/index.tsx
  src/store/store.ts
  src/store/userSlice.ts
  src/types/member.ts
Labels: feat

#63 Feat/요금제비교
  src/apis/planApi.ts
  src/components/BottomSheet/PlanList.tsx
  src/components/DropdownSelector.tsx
  src/components/PlanCompare.tsx
  src/pages/Compare.tsx
  src/utils/formatNumber.ts
Labels: feat

#62 Feat/요금제 상세 페이지 구현 및 반응형 처리 완료 & 리뷰 필터 모달 & 요금제 비교 페이지 최종
  src/components/BenefitDropBar.tsx
  src/components/BottomSheet/CompareBottomBar.tsx
  src/components/BottomSheet/PlanBottomSheet.tsx
  src/components/ChatbotButton.tsx
  src/components/DropdownSelector.tsx
  src/components/Modal/BaseModal.tsx
  src/components/Modal/Review/AllReviewListContent.tsx
  src/components/Modal/Review/ReviewModal.tsx
  src/components/PlanCompare.tsx
  src/components/PlanDetail/PlanBottomBar.tsx
  src/components/PlanDetail/PlanTopBanner.tsx
  src/components/ReviewCard.tsx
  src/context/ToastContext.tsx
  src/data/benefits.ts
  src/default.tsx
  src/hooks/useHorizontalScroll.ts
  src/pages/Compare.tsx
  src/pages/ComparePage.tsx
  src/pages/MainPage.tsx
  src/pages/PlanDetailPage.tsx
  src/router/index.tsx
  src/store/userSlice.ts
  tailwind.config.js
Labels: feat, cleanup, style

#70 feat: 요금제 변경 API 요청에 csrf 추가
  src/apis/PlansApi.ts
Labels: refactoring
